# Basic
gpu_id: 0

# dataset
data_path: "./data/"
filename: 'unit2_2307-2312_I+P_part1.csv'   # src_dataset
test_path: './data/unit2_2307-2312_I+P.csv'
# Graph
graph_path : "./Gene_graph/Graph_data1"
graph_file: ['train_graph_8.xlsx']

# training config
input_len: 3024 # optimal
output_len: 1008
capacity: 24
out_capacity: 24
patient: 20
var_len: 1 # diff should +1

# model general param
gcn_k: 3   # for GCN
layers: 1  #num of model
dropout: 0.1  # dropout rate

# TCN-GCN model param
ks: 3   # kernel size of CausalConv2d
channels_list: [16, 32]   # feature dimension 1->16->32...
d0: 1   # initial dilated rate

# GRU_GCN / GCN_LSTM / AGCRN model param
hidden_dim: 16   #hidden layer dimension of GRU
embed_dim: 10

# data setting
binary: True
weight_adj_epsilon: 0.4
dtw_topk: 2
train_normal_flag: True
test_normal_flag: True

#model
seed: 3407
num_workers: 0 #
epoch: 200
batch_size: 32 # optimal 16
output_path: "./output/"
log_per_steps: 1000
lr: 0.005      # optimal
clip_norm: 5 #?
weight_decay: 0 #? trick
learner: "adam" # 1
lr_decay: False #? trick
lr_scheduler_type: None #?
lr_eta_min: 0.00001 #?
lr_decay_ratio: 0.1 #?
lr_warmup_epoch: 5 #?
lr_warmup_init: 0.000001 #?
loss: "FilterMSELoss" #
save_data_recon_er: False
